name: Template action
description: Template action description

inputs:
  githubToken:
    required: true
    description: GitHub access token
  failOnNotAllowedCommits:
    required: true
    default: 'true'
    description: Fail on not allowed commits
  versionIncrementMode:
    required: true
    default: 'patch'
    description: "Which part of version should be incremented. Allowed values: 'major', 'minor', 'patch'."
  versionTagPrefix:
    required: false
    description: Prefix for new Git version tag
  allowedVersionTagPrefixes:
    required: false
    description: Allowed prefixes for Git version tags
  expectedFilesToChange:
    required: false
    description: One of these files should be changed to make a new release. Glob syntax is supported.
  allowedCommitPrefixes:
    required: false
    description: Allowed commit messages prefixes
  allowedPullRequestLabels:
    required: false
    description: Allowed Pull Request labels
  skippedChangelogCommitPrefixes:
    required: false
    description: Commit messages that won't be displayed in changelog
  dependencyUpdatesPullRequestLabels:
    required: false
    description: Labels of Pull Requests that update dependencies (i.e. PRs from tools like Dependabot, Renovate, etc)
  dependencyUpdatesAuthors:
    required: false
    default: 'dependabot[bot], renovate[bot]'
    description: Authors of Pull Requests that update dependencies (i.e. PRs from tools like Dependabot, Renovate, etc)
  actionPathsAllowedToFail:
    required: false
    description: Paths of GitHub actions are that are allowed to fail
  dryRun:
    required: true
    default: 'false'
    description: Set to 'true' to enable dry run

runs:
  using: node20
  main: 'dist/index.js'
