name: Template action
description: Template action description

inputs:
  githubToken:
    required: true
    default: '${{github.token}}'
    description: GitHub access token
  versionIncrementMode:
    required: true
    default: 'patch'
    description: "Which part of version should be incremented. Allowed values: 'major', 'minor', 'patch'."
  versionTagPrefix:
    required: false
    description: Prefix for new Git version tag
  allowedVersionTagPrefixes:
    required: false
    description: Allowed prefixes for Git version tags
  expectedFilesToChange:
    required: false
    description: One of these files should be changed to make a new release. Glob syntax is supported.
  allowedCommitPrefixes:
    required: false
    description: Allowed commit messages prefixes
  allowedPullRequestLabels:
    required: false
    description: Allowed Pull Request labels
  dryRun:
    required: true
    default: 'false'
    description: Set to 'true' to enable dry run

runs:
  using: node16
  main: 'dist/index.js'
